apiVersion: v1
kind: ConfigMap
metadata:
  name: taskify-backend-config
  namespace: taskify
data:
  SPRING_APPLICATION_NAME: "taskify-backend"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:taskifydb"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_H2_CONSOLE_ENABLED: "true"
  JWT_EXPIRATION: "86400000"
  CORS_ALLOWED_ORIGINS: "http://localhost:30300"
