apiVersion: v1
kind: Secret
metadata:
  name: taskify-backend-secret
  namespace: taskify
type: Opaque
stringData:
  JWT_SECRET: "e6b6916f867d228a9ae07557b003b672a52a7a77a569fec147565f9ed6f4bb904dcb19b1"
  SPRING_DATASOURCE_PASSWORD: ""
