apiVersion: v1
kind: Service
metadata:
  name: taskify-backend
  namespace: taskify
  labels:
    app: taskify-backend
spec:
  type: NodePort
  selector:
    app: taskify-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30800
    protocol: TCP
    name: http
