apiVersion: v1
kind: Service
metadata:
  name: taskify-frontend
  namespace: taskify
  labels:
    app: taskify-frontend
spec:
  type: NodePort
  selector:
    app: taskify-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    protocol: TCP
    name: http
